<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CompressionEnabled>false</CompressionEnabled>
    <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../BaseSite.Web/BaseSite.Web.csproj" />
    <ProjectReference Include="../../BaseSite/BaseSite.Api.csproj" />
  </ItemGroup>
</Project>
