<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version>2.0.0</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\Images\Elevator.jpg" />
    <Content Remove="wwwroot\Images\logo-final.jpg" />
    <Content Remove="wwwroot\Images\logo.svg" />
    <Content Remove="wwwroot\Images\pishfactor.png" />
    <Content Remove="wwwroot\Images\System\small_loading.gif" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\Images\Elevator.jpg" />
    <None Include="wwwroot\Images\logo-final.jpg" />
    <None Include="wwwroot\Images\logo.svg" />
    <None Include="wwwroot\Images\pishfactor.png" />
    <None Include="wwwroot\Images\System\small_loading.gif" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="9.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServiceDefaults\ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\BaseSite\Contents\css\bootstrap.css" Link="wwwroot\Contents\css\bootstrap.css" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\BaseSite\Contents\css\bootstrap-rtl.css" Link="wwwroot\Contents\css\bootstrap-rtl.css" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\BaseSite\Contents\css\MyStyle\PrintPA4.css" Link="wwwroot\Contents\css\MyStyle\PrintPA4.css" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\BaseSite\Contents\css\MyStyle\PrintBill.css" Link="wwwroot\Contents\css\MyStyle\PrintBill.css" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\BaseSite\Contents\js\jquery-3.1.1.js" Link="wwwroot\Contents\js\jquery-3.1.1.js" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\BaseSite\Contents\js\printThis.js" Link="wwwroot\Contents\js\printThis.js" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\BaseSite\Contents\js\autoNumeric.js" Link="wwwroot\Contents\js\autoNumeric.js" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
